# Load custom actions from the actions directory

# Clone this into a elizaConfig.yaml file that is ignored by git

# Paths are relative to the core/src directory

plugins:
    - name: cosmo-play
      enabled: true
      settings:
          API_BASE_URL: http://localhost:3000,
          API_TOKEN: 123123,
